[phases.setup]
nixPkgs = ["python3", "nodejs_22", "ffmpeg"]

[phases.build]
cmds = [
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /app/yt-dlp",
  "chmod +x /app/yt-dlp"
]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node server.js"