[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "nodejs_22", "ffmpeg"]

[phases.build]
cmds = ["pip3 install -U yt-dlp --break-system-packages"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node server.js"